export const hugeTechnologies = [
    'Node.js',
    'Kotlin',
    'PHP',
    'Java',
    'Python',
    'C',
    'C++',
    '.NET',
    'C#'
];
export const languages = [
    {value: "Java", label: "Java"},
    {value: "C", label: "C"},
    {value: "Python", label: "Python"},
    {value: "Go", label: "Golang"},
    {value: "JavaScript", label: "JavaScript"},
];

export const technologies = [
    {value: "AWS", label: "AWS"},
    {value: "Node.js", label: "Node.js"},
    {value: "Java", label: "Java"},
    {value: "Angularjs", label: "Angularjs"},
    {value: "React", label: "React"},
    {value: "PHP", label: "PHP"},
    {value: "Laravel", label: "Laravel"},
    {value: "Vue.js", label: "Vue.js"},
    {value: "React Native", label: "React Native"},
    {value: "GraphQL", label: "GraphQL"},
    {value: "DevOps", label: "DevOps"},
    {value: "Typescript", label: "Typescript"},
    {value: "Angular2+", label: "Angular2+"},
    {value: "Android/Kotlin", label: "Android/Kotlin"},
    {value: "Android", label: "Android"},
    {value: "Kotlin", label: "Kotlin"},
    {value: "Kubernetes", label: "Kubernetes"},
    {value: "DynamoDB", label: "DynamoDB"},
    {value: "ElasticSearch", label: "ElasticSearch"},
    {value: "C", label: "C"},
    {value: "Drupal", label: "Drupal"},
    {value: "Vagrant", label: "Vagrant"},
    {value: ".NET", label: ".NET"},
    {value: "Microservices", label: "Microservices"},
    {value: "Swift", label: "Swift"},
    {value: "Docker", label: "Docker"},
    {value: "MySQL", label: "MySQL"},
    {value: "SASS", label: "SASS"},
    {value: "Jira", label: "Jira"},
    {value: "Apache", label: "Apache"},
    {value: "Jenkins", label: "Jenkins"},
    {value: "CI/CD", label: "CI/CD"},
    {value: "SOAP", label: "SOAP"},
    {value: "Bitbucket", label: "Bitbucket"},
    {value: "Kotlin", label: "Kotlin"},
    {value: "Joomla", label: "Joomla"},
    {value: "Nginx", label: "Nginx"},
    {value: "Cordova", label: "Cordova"},
    {value: "Wordpress", label: "Wordpress"},
    {value: "onfluence", label: "Confluence"},
    {value: "C++", label: "C++"},
    //{value: "Information Technology", label: "Information Technology"},
    {value: "Symfony", label: "Symfony"},
    {value: "Bash", label: "Bash"},
    {value: "Selenium", label: "Selenium"},
    {value: "CakePHP", label: "CakePHP"},
    {value: "Ionic", label: "Ionic"},
    {value: "jQuery", label: "jQuery"},
    {value: "DNS", label: "DNS"},
    {value: "SQLite", label: "SQLite"},
    {value: "Webpack", label: "Webpack"},
    {value: "Electron", label: "Electron"},
    {value: "HTML", label: "HTML"},
    {value: "Magento", label: "Magento"},
    {value: "Agile", label: "Agile"},
    {value: "C#", label: "C#"},
    {value: "Cloud", label: "Cloud"},
    {value: "Python", label: "Python"},
    {value: "Javascript", label: "Javascript"},
    {value: "Scrum", label: "Scrum"},
    {value: "Flash", label: "Flash"},
    {value: "CSS", label: "CSS"},
    {value: "SaaS", label: "SaaS"},
    {value: "Bootstrap", label: "Bootstrap"},
    {value: "Serverless", label: "Serverless"},
    {value: "ECS", label: "ECS"},
];